In [ ]:
import torch

In [ ]:
import torch.nn as nn

In [ ]:
torch.manual_seed(0)
torch.set_printoptions(precision=7)

# NLP Example
batch, sentence_length, embedding_dim = 3, 5, 10
embedding = torch.randn(batch, sentence_length, embedding_dim)
layer_norm = nn.LayerNorm(embedding_dim)
layer_norm.bias = nn.Parameter(torch.randn(embedding_dim))
layer_norm.weight = nn.Parameter(torch.randn(embedding_dim))
# Activate module
out = layer_norm(embedding)

In [ ]:
print(embedding)

tensor([[[-1.1258398e+00, -1.1523602e+00, -2.5057858e-01, -4.3387881e-01,
           8.4871036e-01,  6.9200915e-01, -3.1601277e-01, -2.1152194e+00,
           3.2227492e-01, -1.2633348e+00],
         [ 3.4998319e-01,  3.0813393e-01,  1.1984151e-01,  1.2376579e+00,
           1.1167772e+00, -2.4727815e-01, -1.3526537e+00, -1.6959312e+00,
           5.6665063e-01,  7.9350835e-01],
         [ 5.9883946e-01, -1.5550951e+00, -3.4136039e-01,  1.8530061e+00,
           7.5018948e-01, -5.8549756e-01, -1.7339675e-01,  1.8347794e-01,
           1.3893661e+00,  1.5863342e+00],
         [ 9.4629836e-01, -8.4367675e-01, -6.1358309e-01,  3.1592742e-02,
          -4.9267697e-01,  2.4841475e-01,  4.3969584e-01,  1.1241119e-01,
           6.4079237e-01,  4.4115627e-01],
         [-1.0230965e-01,  7.9244399e-01, -2.8966770e-01,  5.2507486e-02,
           5.2286047e-01,  2.3022053e+00, -1.4688939e+00, -1.5866888e+00,
          -6.7308992e-01,  8.7283123e-01]],

        [[ 1.0553575e+00,  1.7784372e-01, -

In [ ]:
print(layer_norm.bias)

Parameter containing:
tensor([ 0.4134675,  0.9219105, -1.3675891, -0.1525318, -0.9588874,  0.7916716,
         0.3360150,  1.0042887,  1.4007128, -1.7721887], requires_grad=True)


In [ ]:
print(layer_norm.weight)

Parameter containing:
tensor([ 1.5151961,  0.3698294,  0.2814750,  0.5603455,  0.6310731,  1.3468844,
        -0.4519350, -0.4052854,  1.4875096, -0.2229669], requires_grad=True)


In [ ]:
print(out)

tensor([[[-6.8014061e-01,  6.4403117e-01, -1.2956674e+00, -1.2403681e-01,
          -2.3047555e-02,  2.5533540e+00,  2.5355646e-01,  1.7445250e+00,
           2.7322421e+00, -1.5770301e+00],
         [ 7.9009211e-01,  9.9713355e-01, -1.3675367e+00,  5.2357060e-01,
          -2.7977607e-01,  2.5827196e-01,  1.0541366e+00,  1.7984344e+00,
           2.1182899e+00, -1.9343382e+00],
         [ 7.5309038e-01,  2.2255601e-01, -1.5643772e+00,  6.6318333e-01,
          -7.2364217e-01, -4.7288340e-01,  5.7743472e-01,  1.0787560e+00,
           2.8888793e+00, -2.0383809e+00],
         [ 2.7724974e+00,  2.9262000e-01, -1.7286386e+00, -2.1317394e-01,
          -1.6294701e+00,  1.1775293e+00,  4.9175829e-02,  9.8852319e-01,
           2.8893659e+00, -1.9142965e+00],
         [ 2.1496688e-01,  1.1734052e+00, -1.4522665e+00, -1.4730658e-01,
          -6.8394828e-01,  3.5508032e+00,  9.5504200e-01,  1.6026921e+00,
           4.3623909e-01, -1.9400593e+00]],

        [[ 1.0221230e+00,  7.8490067e-01, -

In [ ]:
mean = torch.mean(embedding.flatten())
print(out)

tensor([[[-6.8014061e-01,  6.4403117e-01, -1.2956674e+00, -1.2403681e-01,
          -2.3047555e-02,  2.5533540e+00,  2.5355646e-01,  1.7445250e+00,
           2.7322421e+00, -1.5770301e+00],
         [ 7.9009211e-01,  9.9713355e-01, -1.3675367e+00,  5.2357060e-01,
          -2.7977607e-01,  2.5827196e-01,  1.0541366e+00,  1.7984344e+00,
           2.1182899e+00, -1.9343382e+00],
         [ 7.5309038e-01,  2.2255601e-01, -1.5643772e+00,  6.6318333e-01,
          -7.2364217e-01, -4.7288340e-01,  5.7743472e-01,  1.0787560e+00,
           2.8888793e+00, -2.0383809e+00],
         [ 2.7724974e+00,  2.9262000e-01, -1.7286386e+00, -2.1317394e-01,
          -1.6294701e+00,  1.1775293e+00,  4.9175829e-02,  9.8852319e-01,
           2.8893659e+00, -1.9142965e+00],
         [ 2.1496688e-01,  1.1734052e+00, -1.4522665e+00, -1.4730658e-01,
          -6.8394828e-01,  3.5508032e+00,  9.5504200e-01,  1.6026921e+00,
           4.3623909e-01, -1.9400593e+00]],

        [[ 1.0221230e+00,  7.8490067e-01, -

In [ ]:
print(mean)

tensor(0.0465393)


In [ ]:
print(embedding)

tensor([[[-1.1258398e+00, -1.1523602e+00, -2.5057858e-01, -4.3387881e-01,
           8.4871036e-01,  6.9200915e-01, -3.1601277e-01, -2.1152194e+00,
           3.2227492e-01, -1.2633348e+00],
         [ 3.4998319e-01,  3.0813393e-01,  1.1984151e-01,  1.2376579e+00,
           1.1167772e+00, -2.4727815e-01, -1.3526537e+00, -1.6959312e+00,
           5.6665063e-01,  7.9350835e-01],
         [ 5.9883946e-01, -1.5550951e+00, -3.4136039e-01,  1.8530061e+00,
           7.5018948e-01, -5.8549756e-01, -1.7339675e-01,  1.8347794e-01,
           1.3893661e+00,  1.5863342e+00],
         [ 9.4629836e-01, -8.4367675e-01, -6.1358309e-01,  3.1592742e-02,
          -4.9267697e-01,  2.4841475e-01,  4.3969584e-01,  1.1241119e-01,
           6.4079237e-01,  4.4115627e-01],
         [-1.0230965e-01,  7.9244399e-01, -2.8966770e-01,  5.2507486e-02,
           5.2286047e-01,  2.3022053e+00, -1.4688939e+00, -1.5866888e+00,
          -6.7308992e-01,  8.7283123e-01]],

        [[ 1.0553575e+00,  1.7784372e-01, -

In [ ]:
torch.var(embedding.flatten(), correction = 0)

tensor(1.0097520)

In [ ]:
mat = torch.rand(10,7)
outmat = torch.matmul(embedding, mat)
print(outmat.size())
print(mat)

torch.Size([3, 5, 7])
tensor([[0.3202675, 0.9217443, 0.6808038, 0.5633130, 0.4962780, 0.4011592,
         0.5627332],
        [0.3858277, 0.4964868, 0.5637965, 0.1088974, 0.2379343, 0.9037464,
         0.0942267],
        [0.4640969, 0.9946194, 0.6806185, 0.5141565, 0.0666950, 0.7476889,
         0.1438596],
        [0.3580679, 0.3322418, 0.4259563, 0.5054691, 0.9124038, 0.5624194,
         0.9478464],
        [0.8058562, 0.1838930, 0.7242520, 0.1465520, 0.2880874, 0.6470613,
         0.6650960],
        [0.8751140, 0.3390421, 0.5008004, 0.7574118, 0.0164539, 0.8614903,
         0.0865388],
        [0.5068913, 0.4149916, 0.2366635, 0.5660855, 0.9134594, 0.3538402,
         0.2031530],
        [0.3150806, 0.0044258, 0.7256970, 0.2598681, 0.1663299, 0.2119493,
         0.7874780],
        [0.7647868, 0.8837609, 0.6813616, 0.3330202, 0.3602759, 0.6477150,
         0.9110174],
        [0.6359461, 0.2634273, 0.2649613, 0.0272655, 0.6080240, 0.2194088,
         0.0542121]])


In [ ]:
print(outmat)

tensor([[[-1.1708975, -1.8010461, -2.5352421, -1.1150119, -2.2821302,
          -1.4077140, -2.0698471],
         [ 1.1313159,  1.2684772,  0.7512274, -0.1018000,  0.8708464,
           1.4172126,  1.0866387],
         [ 2.2303445,  1.5700667,  1.7970978,  1.0510538,  3.1388011,
           0.8282740,  3.8069866],
         [ 0.5533872,  0.7126963,  0.2711436,  0.7611715,  1.0383805,
          -0.2373878,  0.8740477],
         [ 1.3891894, -0.0763586,  0.0075252,  0.2824090, -0.9626103,
           1.7092115, -1.5415950]],

        [[ 3.5918145,  2.7284651,  3.0650239,  0.6179950,  2.6810713,
           1.9359235,  2.5991089],
         [ 1.4984508, -0.3535559,  0.1858113,  0.8150347,  0.6733762,
           0.0172896, -1.5039616],
         [-1.5837415, -2.6802733, -1.3995588, -2.1335082, -1.2616304,
          -2.2104676, -0.7757092],
         [ 2.0906959,  0.2628427,  1.1113933,  0.0744028,  2.6184402,
           0.9468732,  0.8116964],
         [ 0.1989748, -1.7508932, -2.2728944, -0.8362

In [ ]:
print(torch.transpose(mat, 0 ,1))

tensor([[0.3202675, 0.3858277, 0.4640969, 0.3580679, 0.8058562, 0.8751140,
         0.5068913, 0.3150806, 0.7647868, 0.6359461],
        [0.9217443, 0.4964868, 0.9946194, 0.3322418, 0.1838930, 0.3390421,
         0.4149916, 0.0044258, 0.8837609, 0.2634273],
        [0.6808038, 0.5637965, 0.6806185, 0.4259563, 0.7242520, 0.5008004,
         0.2366635, 0.7256970, 0.6813616, 0.2649613],
        [0.5633130, 0.1088974, 0.5141565, 0.5054691, 0.1465520, 0.7574118,
         0.5660855, 0.2598681, 0.3330202, 0.0272655],
        [0.4962780, 0.2379343, 0.0666950, 0.9124038, 0.2880874, 0.0164539,
         0.9134594, 0.1663299, 0.3602759, 0.6080240],
        [0.4011592, 0.9037464, 0.7476889, 0.5624194, 0.6470613, 0.8614903,
         0.3538402, 0.2119493, 0.6477150, 0.2194088],
        [0.5627332, 0.0942267, 0.1438596, 0.9478464, 0.6650960, 0.0865388,
         0.2031530, 0.7874780, 0.9110174, 0.0542121]])


In [ ]:
matbias = torch.rand(7)
outbias = outmat = torch.matmul(embedding, mat) + matbias

In [ ]:
print(matbias)
print(outbias)

tensor([0.9384382, 0.1752944, 0.4431192, 0.6432468, 0.5159292, 0.1635591,
        0.0958391])
tensor([[[-0.2324592, -1.6257517, -2.0921228, -0.4717652, -1.7662010,
          -1.2441549, -1.9740080],
         [ 2.0697541,  1.4437716,  1.1943467,  0.5414468,  1.3867755,
           1.5807717,  1.1824778],
         [ 3.1687827,  1.7453611,  2.2402170,  1.6943005,  3.6547303,
           0.9918332,  3.9028258],
         [ 1.4918255,  0.8879907,  0.7142628,  1.4044182,  1.5543096,
          -0.0738287,  0.9698868],
         [ 2.3276277,  0.0989358,  0.4506444,  0.9256557, -0.4466811,
           1.8727705, -1.4457558]],

        [[ 4.5302529,  2.9037595,  3.5081432,  1.2612418,  3.1970005,
           2.0994825,  2.6949482],
         [ 2.4368889, -0.1782615,  0.6289306,  1.4582815,  1.1893053,
           0.1808487, -1.4081224],
         [-0.6453033, -2.5049789, -0.9564396, -1.4902614, -0.7457013,
          -2.0469084, -0.6798700],
         [ 3.0291340,  0.4381371,  1.5545125,  0.7176495,  3.134